# Class 11
## Date: 05-04-2026

## **Pandas**

In [3]:
import pandas as pd
import numpy as np

### **Introduction to Pandas**
Pandas is a powerful Python library for data manipulation and analysis. It provides data structures like Series (1D) and DataFrame (2D) that make working with structured data easy.

Key features:
- Reading/writing data from various formats (CSV, Excel, SQL, etc.)
- Data cleaning and preprocessing
- Powerful indexing and selection
- Grouping and aggregation operations
- Time series functionality

### **Uploading data**
- from path
- from environment

In [4]:
df= pd.read_csv("../data/retail_2016_2017.csv")
df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [53]:
df= pd.read_csv(r"C:\Users\Shreyit\Code\Sem IV Python\data\retail_2016_2017.csv")
df
#from path

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

### **Reading CSV Files**
- `pd.read_csv()` is the primary function to read CSV files
- **Relative paths**: `"../data/filename.csv"` - relative to current working directory
- **Absolute paths**: `r"C:\full\path\to\file.csv"` - full path from root
- The `r` prefix before strings prevents backslash escaping in Windows paths
- Always check your working directory with `os.getcwd()` when using relative paths

In [66]:
import os
os.getcwd()

'c:\\Users\\Shreyit\\Code\\Sem IV Python\\Class ipynb Notebook'

### **Series**
A Series is a one-dimensional labeled array in pandas. It's like a column in a spreadsheet or a single column of data.

Key characteristics:
- Has an index (labels for each element)
- Can hold any data type
- Supports vectorized operations
- Similar to a dictionary or enhanced NumPy array

In [54]:
array=np.arange(5)
pd_series= pd.Series(array, name='my first panda series')

In [55]:
array

array([0, 1, 2, 3, 4])

**Creating Series from Arrays:**
- `pd.Series(data, index, name)` creates a Series
- `data` can be a list, array, or scalar value
- `index` provides labels (defaults to 0,1,2...)
- `name` gives the Series a name for identification

In [56]:
pd_series

0    0
1    1
2    2
3    3
4    4
Name: my fierst panda series, dtype: int64

In [57]:
d= {"State": ['AP','UP','HP'],
   "Size":[10,20,30],
   "population":["HIGH","HIGH","LOW"]}
pd.DataFrame(d)
#Create a dictionary and convert to DataFrame

  State  Size population
0    AP    10       HIGH
1    UP    20       HIGH
2    HP    30        LOW

**Creating DataFrames:**
- `pd.DataFrame(data)` creates a 2D table
- `data` can be a dictionary (keys become columns), list of lists, or other structures
- Each column is a Series
- Supports various data types per column

In [58]:
sales= [0,23,4,3,54,23,0,2,12,54,]
sales_series=pd.Series(sales, name='sales series')
sales_series

0     0
1    23
2     4
3     3
4    54
5    23
6     0
7     2
8    12
9    54
Name: sales series, dtype: int64

In [59]:
sales_series.astype("float")
# change the data type, but only for this cell
# pass in another variable to change type

0     0.0
1    23.0
2     4.0
3     3.0
4    54.0
5    23.0
6     0.0
7     2.0
8    12.0
9    54.0
Name: sales series, dtype: float64

In [60]:
sales_series.astype('bool')
# zero= false, other= true

0    False
1     True
2     True
3     True
4     True
5     True
6    False
7     True
8     True
9     True
Name: sales series, dtype: bool

**Data Type Conversion:**
- `.astype(dtype)` converts Series data types
- Common types: 'int64', 'float64', 'object' (string), 'bool'
- Important for memory efficiency and operations
- Boolean conversion: 0 → False, non-zero → True

In [61]:
sales=[0,5,155,0,518,0,1287,616,317,325]
month=['jan','feb','march','april','may','june','july','august','september','october']
sales_month= pd.Series(sales, index=month, name='Sales')
sales_month.sort_values() # sort values, sort_index() sort index 
# put (ascending=FALSE) to put in descending order, and to make it permanent, put inplace= TRUE, otherwise it sorts only for this line

jan             0
april           0
june            0
feb             5
march         155
september     317
october       325
may           518
august        616
july         1287
Name: Sales, dtype: int64

**Sorting Series:**
- `.sort_values()` sorts by values (ascending by default)
- `.sort_index()` sorts by index labels
- `ascending=False` for descending order
- `inplace=True` modifies the original Series permanently

### **Indexing and Selection: ILOC vs LOC**
- **ILOC**: Position-based indexing (like Python lists)
  - Uses integer positions: `series.iloc[0]`, `series.iloc[0:3]`
  - Always uses numbers, regardless of index labels
- **LOC**: Label-based indexing
  - Uses index labels: `series.loc['jan']`, `series.loc['jan':'march']`
  - Works with custom index labels

In [62]:
sales_month.iloc[0:4]

jan        0
feb        5
march    155
april      0
Name: Sales, dtype: int64

In [63]:
sales_month.iloc[[2,5,9]]
# specific values

march      155
june         0
october    325
Name: Sales, dtype: int64

In [64]:
sales_month.loc['july':'october']

july         1287
august        616
september     317
october       325
Name: Sales, dtype: int64