# Class 14
## Date: 25-04-2026

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns

In [43]:
df = pd.read_pickle('../data/groceries_with_new_columns.pkl')
df.head()

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday

In [44]:
stdf = pd.read_csv('../data/student_data.csv')
stdf.head()

,Hours of Sleep,Hours Studied,Grade on Test,Grade in Class,Cups of Coffee
0,10.602667,4.586892,99,99.187294,5
1,8.172997,4.405120,72,67.070903,3
2,6.430132,0.519630,52,39.644696,4
3,7.963793,5.004348,80,61.843705,1
4,8.279421,2.984489,87,103.495002,0

In [48]:
df[(df['Subcategory'] != 'Fruit') & (df['Inventory'] >= 100) & (df['Percent Inventory'] > 5)]

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
11,P100021,100021,Produce,Meat,Chicken (Organic),True,10.49,284,5.8,,2023-06-13 07:20:00,07:20:00,2023-06-17,Saturday
13,P100023,100023,Produce,Dairy,Butter,False,3.50,400,8.2,,2023-06-13 08:35:00,08:35:00,2023-06-17,Saturday
16,P100026,100026,Produce,Dairy,Yogurt,False,1.00,432,8.9,,2023-06-13 08:41:00,08:41:00,2023-06-17,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday

In [50]:
df['Category'].value_counts()

Category
Produce    17
Pantry      4
Frozen      4
Name: count, dtype: int64

- #### _**inplace = True** dosent work if filtering_
- #### _**'~'** checks the opposite_ (like if I have to remove 2 val from a cat out of 50 we will not enter the 48 one instead we will use tilda and then put the 2 val which we do not want)

In [59]:
df_cat = ['Frozen', 'Pantry']  # instead of putting & everytime like above this is better
df[~df['Category'].isin(df_cat)]  # isin - a membership test

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday
5,P100015,100015,Produce,Fruit,Watermelon,False,5.99,99,2.0,,2023-06-12 19:15:00,19:15:00,2023-06-15,Thursday
6,P100016,100016,Produce,Vegetable,Cabbage,False,1.78,78,1.6,,2023-06-12 19:25:00,19:25:00,2023-06-15,Thursday
7,P100017,100017,Produce,Vegetable,Carrots,False,2.00,200,4.1,,2023-06-12 18:05:00,18:05:00,2023-06-15,Thursday
8,P100018,100018,Produce,Vegetable,Celery,False,1.99,50,1.0,,2023-06-12 16:42:00,16:42:00,2023-06-15,Thursday
9,P100019,100019,Produce,Vegetable,Cucumber,False,0.99,230,4.7,,2023-06-12 17:47:00,17:47:00,2023-06-15,Thursday
10,P100020,100020,Produce,Meat,Beef,False,8.99,145,3.0,,2023-06-13 07:00:00,07:00:00,2023-06-17,Saturday
11,P100021,100021,Produce,Meat,Chicken (Organic),True,10.49,284,5.8,,2023-06-13 07:20:00,07:20:00,2023-06-17,Saturday
12,P100022,100022,Produce,Meat,Turkey,False,7.99,188,3.9,,2023-06-13 07:32:00,07:32:00,2023-06-17,Saturday
13,P100023,100023,Produce,Dairy,Butter,False,3.50,400,8.2,,2023-06-13 08:35:00,08:35:00,2023-06-17,Saturday
14,P100024,100024,Produce,Dairy,Eggs,False,3.29,234,4.8,,2023-06-13 08:54:00,08:54:00,2023-06-17,Saturday
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
16,P100026,100026,Produce,Dairy,Yogurt,False,1.00,432,8.9,,2023-06-13 08:41:00,08:41:00,2023-06-17,Saturday

### **str.contains**
- case sensitive, so use **_case=False_**

In [63]:
df[df['Item'].str.contains('Apple')]

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.5,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.5,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday

### **sort_index()**
| Parameter | Description | Options |
|-----------|-------------|---------|
| axis | Sort by rows or columns | 0 (rows/index), 1 (columns) |
| ascending | Sort order | True (ascending - default), False (descending) |
| inplace | Modify original DataFrame | True, False (default) |
| na_position | Where to put NaN values | 'last' (default), 'first' |

In [71]:
df.sort_index(axis = 1, ascending=False)

,Subcategory,Shipment_Date_DOW,Product_ID_Num,Product_ID,Price_Dollars,Percent Inventory,Organic,Next_Scheduled_Shipment,Low Inventory,Last_Updated_Time,Last_Updated,Item,Inventory,Category
0,Fruit,Thursday,100010,P100010,1.50,7.2,False,2023-06-15,,15:35:00,2023-06-12 15:35:00,Apple,349,Produce
1,Fruit,Thursday,100011,P100011,0.40,10.3,False,2023-06-15,,18:30:00,2023-06-12 18:30:00,Banana,500,Produce
2,Fruit,Thursday,100012,P100012,4.00,4.1,False,2023-06-15,,17:22:00,2023-06-12 17:22:00,Grapes,200,Produce
3,Fruit,Thursday,100013,P100013,0.99,1.0,False,2023-06-15,,16:29:00,2023-06-12 16:29:00,Grapefruit,50,Produce
4,Fruit,Thursday,100014,P100014,3.99,3.0,True,2023-06-15,,18:10:00,2023-06-12 18:10:00,Organic Strawberries,148,Produce
5,Fruit,Thursday,100015,P100015,5.99,2.0,False,2023-06-15,,19:15:00,2023-06-12 19:15:00,Watermelon,99,Produce
6,Vegetable,Thursday,100016,P100016,1.78,1.6,False,2023-06-15,,19:25:00,2023-06-12 19:25:00,Cabbage,78,Produce
7,Vegetable,Thursday,100017,P100017,2.00,4.1,False,2023-06-15,,18:05:00,2023-06-12 18:05:00,Carrots,200,Produce
8,Vegetable,Thursday,100018,P100018,1.99,1.0,False,2023-06-15,,16:42:00,2023-06-12 16:42:00,Celery,50,Produce
9,Vegetable,Thursday,100019,P100019,0.99,4.7,False,2023-06-15,,17:47:00,2023-06-12 17:47:00,Cucumber,230,Produce
10,Meat,Saturday,100020,P100020,8.99,3.0,False,2023-06-17,,07:00:00,2023-06-13 07:00:00,Beef,145,Produce
11,Meat,Saturday,100021,P100021,10.49,5.8,True,2023-06-17,,07:20:00,2023-06-13 07:20:00,Chicken (Organic),284,Produce
12,Meat,Saturday,100022,P100022,7.99,3.9,False,2023-06-17,,07:32:00,2023-06-13 07:32:00,Turkey,188,Produce
13,Dairy,Saturday,100023,P100023,3.50,8.2,False,2023-06-17,,08:35:00,2023-06-13 08:35:00,Butter,400,Produce
14,Dairy,Saturday,100024,P100024,3.29,4.8,False,2023-06-17,,08:54:00,2023-06-13 08:54:00,Eggs,234,Produce
15,Dairy,Saturday,100025,P100025,4.49,0.7,False,2023-06-17,Low Inventory,08:37:00,2023-06-13 08:37:00,Milk (Soy),32,Produce
16,Dairy,Saturday,100026,P100026,1.00,8.9,False,2023-06-17,,08:41:00,2023-06-13 08:41:00,Yogurt,432,Produce
17,Snacks,Saturday,100027,P100027,1.50,0.6,True,2023-06-24,Low Inventory,12:02:00,2023-06-10 12:02:00,Apple Sauce - organic,27,Pantry
18,Snacks,Saturday,100028,P100028,2.50,7.5,False,2023-06-24,,12:12:00,2023-06-10 12:12:00,Chips,365,Pantry
19,Snacks,Saturday,100029,P100029,5.39,7.0,False,2023-06-24,,12:24:00,2023-06-10 12:24:00,Cookies (Oatmeal),340,Pantry
20,Snacks,Saturday,100030,P100030,2.99,0.1,False,2023-06-24,Low Inventory,12:38:00,2023-06-10 12:38:00,Raisins,5,Pantry
21,Frozen Snacks,Wednesday,100031,P100031,6.99,1.8,False,2023-06-28,,22:02:00,2023-05-28 22:02:00,Chicken Nuggets,85,Frozen
22,Frozen Snacks,Wednesday,100032,P100032,4.96,1.6,False,2023-06-28,,22:05:00,2023-05-28 22:05:00,Spinach Dip,76,Frozen
23,Frozen Fruit,Wednesday,100033,P100033,10.99,3.3,False,2023-06-28,,22:14:00,2023-05-28 22:14:00,Frozen Blueberries,162,Frozen
24,Frozen Fruit,Wednesday,100034,P100034,7.96,3.7,False,2023-06-28,,22:11:00,2023-05-28 22:11:00,Frozen Pineapple,178,Frozen

### **sort_values()**
| Parameter | Description | Options |
|-----------|-------------|---------|
| by | Column name(s) or index level(s) to sort by | string or list of strings |
| axis | Sort by rows or columns | 0 (rows/index), 1 (columns) |
| ascending | Sort order | True (ascending - default), False (descending) |
| inplace | Modify original DataFrame | True, False (default) |
| na_position | Where to put NaN values | 'last' (default), 'first' |
| ignore_index | Reset index after sorting | True, False (default) |
| key | Apply function to values before sorting | callable function |

In [74]:
df.sort_values('Price_Dollars', ascending=False)

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
23,P100033,100033,Frozen,Frozen Fruit,Frozen Blueberries,False,10.99,162,3.3,,2023-05-28 22:14:00,22:14:00,2023-06-28,Wednesday
11,P100021,100021,Produce,Meat,Chicken (Organic),True,10.49,284,5.8,,2023-06-13 07:20:00,07:20:00,2023-06-17,Saturday
10,P100020,100020,Produce,Meat,Beef,False,8.99,145,3.0,,2023-06-13 07:00:00,07:00:00,2023-06-17,Saturday
12,P100022,100022,Produce,Meat,Turkey,False,7.99,188,3.9,,2023-06-13 07:32:00,07:32:00,2023-06-17,Saturday
24,P100034,100034,Frozen,Frozen Fruit,Frozen Pineapple,False,7.96,178,3.7,,2023-05-28 22:11:00,22:11:00,2023-06-28,Wednesday
21,P100031,100031,Frozen,Frozen Snacks,Chicken Nuggets,False,6.99,85,1.8,,2023-05-28 22:02:00,22:02:00,2023-06-28,Wednesday
5,P100015,100015,Produce,Fruit,Watermelon,False,5.99,99,2.0,,2023-06-12 19:15:00,19:15:00,2023-06-15,Thursday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
22,P100032,100032,Frozen,Frozen Snacks,Spinach Dip,False,4.96,76,1.6,,2023-05-28 22:05:00,22:05:00,2023-06-28,Wednesday
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday
13,P100023,100023,Produce,Dairy,Butter,False,3.50,400,8.2,,2023-06-13 08:35:00,08:35:00,2023-06-17,Saturday
14,P100024,100024,Produce,Dairy,Eggs,False,3.29,234,4.8,,2023-06-13 08:54:00,08:54:00,2023-06-17,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
7,P100017,100017,Produce,Vegetable,Carrots,False,2.00,200,4.1,,2023-06-12 18:05:00,18:05:00,2023-06-15,Thursday
8,P100018,100018,Produce,Vegetable,Celery,False,1.99,50,1.0,,2023-06-12 16:42:00,16:42:00,2023-06-15,Thursday
6,P100016,100016,Produce,Vegetable,Cabbage,False,1.78,78,1.6,,2023-06-12 19:25:00,19:25:00,2023-06-15,Thursday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
16,P100026,100026,Produce,Dairy,Yogurt,False,1.00,432,8.9,,2023-06-13 08:41:00,08:41:00,2023-06-17,Saturday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
9,P100019,100019,Produce,Vegetable,Cucumber,False,0.99,230,4.7,,2023-06-12 17:47:00,17:47:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday

### **groupby()**

In [76]:
df.groupby(['Category', 'Subcategory']) ['Price_Dollars'].mean()

Category  Subcategory
Frozen    Frozen Fruit     9.475000
          Frozen Snacks    5.975000
Pantry    Snacks           3.095000
Produce   Dairy            3.070000
          Fruit            2.811667
          Meat             9.156667
          Vegetable        1.690000
Name: Price_Dollars, dtype: float64

In [80]:
df.groupby(['Category']).agg({'Price_Dollars': 'sum', 'Inventory': 'sum'})

          Price_Dollars  Inventory
Category
Frozen            30.90        501
Pantry            12.38        737
Produce           63.38       3619

In [81]:
df.groupby(['Category', 'Subcategory']).agg({'Price_Dollars': 'sum', 'Inventory': 'sum'})

                        Price_Dollars  Inventory
Category Subcategory
Frozen   Frozen Fruit           18.95        340
         Frozen Snacks          11.95        161
Pantry   Snacks                 12.38        737
Produce  Dairy                  12.28       1098
         Fruit                  16.87       1346
         Meat                   27.47        617
         Vegetable               6.76        558

In [83]:
eda = df.groupby(['Category', 'Subcategory']).agg({'Price_Dollars': 'sum', 'Inventory': 'sum', 'Shipment_Date_DOW': 'unique'}) 
eda

                        Price_Dollars  Inventory Shipment_Date_DOW
Category Subcategory
Frozen   Frozen Fruit           18.95        340       [Wednesday]
         Frozen Snacks          11.95        161       [Wednesday]
Pantry   Snacks                 12.38        737        [Saturday]
Produce  Dairy                  12.28       1098        [Saturday]
         Fruit                  16.87       1346        [Thursday]
         Meat                   27.47        617        [Saturday]
         Vegetable               6.76        558        [Thursday]