# Class 12
## Date: 18-04-2026

## **Data Ingestion in Pandas**

In [2]:
import pandas as pd
import numpy as np

### Retail Data

In [3]:
df= pd.read_csv("../data/retail_2016_2017.csv")
df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [20]:
df.shape

(1054944, 6)

In [9]:
df.head(10)

        id        date  store_nbr        family  sales  onpromotion
0  1945944  2016-01-01          1    AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1     BABY CARE    0.0            0
2  1945946  2016-01-01          1        BEAUTY    0.0            0
3  1945947  2016-01-01          1     BEVERAGES    0.0            0
4  1945948  2016-01-01          1         BOOKS    0.0            0
5  1945949  2016-01-01          1  BREAD/BAKERY    0.0            0
6  1945950  2016-01-01          1   CELEBRATION    0.0            0
7  1945951  2016-01-01          1      CLEANING    0.0            0
8  1945952  2016-01-01          1         DAIRY    0.0            0
9  1945953  2016-01-01          1          DELI    0.0            0

In [15]:
df.dtypes

id               int64
date            object
store_nbr        int64
family          object
sales          float64
onpromotion      int64
dtype: object

In [16]:
df.tail()

,id,date,store_nbr,family,sales,onpromotion
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [18]:
df01 = df.copy()
df01

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  object
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 48.3+ MB

In [21]:
df.describe()

                 id     store_nbr         sales   onpromotion
count  1.054944e+06  1.054944e+06  1.054944e+06  1.054944e+06
mean   2.473416e+06  2.750000e+01  4.577225e+02  5.937977e+00
std    3.045362e+05  1.558579e+01  1.317155e+03  1.808632e+01
min    1.945944e+06  1.000000e+00  0.000000e+00  0.000000e+00
25%    2.209680e+06  1.400000e+01  2.000000e+00  0.000000e+00
50%    2.473416e+06  2.750000e+01  2.400000e+01  0.000000e+00
75%    2.737151e+06  4.100000e+01  2.620000e+02  3.000000e+00
max    3.000887e+06  5.400000e+01  1.247170e+05  7.410000e+02

In [22]:
df.describe(include = 'all')

,id,date,store_nbr,family,sales,onpromotion
count,1.054944e+06,1054944,1.054944e+06,1054944,1.054944e+06,1.054944e+06
unique,NaN,592,NaN,33,NaN,NaN
top,NaN,2016-01-01,NaN,AUTOMOTIVE,NaN,NaN
freq,NaN,1782,NaN,31968,NaN,NaN
mean,2.473416e+06,NaN,2.750000e+01,NaN,4.577225e+02,5.937977e+00
std,3.045362e+05,NaN,1.558579e+01,NaN,1.317155e+03,1.808632e+01
min,1.945944e+06,NaN,1.000000e+00,NaN,0.000000e+00,0.000000e+00
25%,2.209680e+06,NaN,1.400000e+01,NaN,2.000000e+00,0.000000e+00
50%,2.473416e+06,NaN,2.750000e+01,NaN,2.400000e+01,0.000000e+00
75%,2.737151e+06,NaN,4.100000e+01,NaN,2.620000e+02,3.000000e+00
max,3.000887e+06,NaN,5.400000e+01,NaN,1.247170e+05,7.410000e+02

In [32]:
df.columns = [col.upper() for col in df.columns]
df.columns

Index(['ID', 'DATE', 'STORE_NBR', 'FAMILY', 'SALES', 'ONPROMOTION'], dtype='object')

In [31]:
df_oil = pd.read_csv("../data/oil.csv")
df_oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [33]:
df.head(7)

        ID        DATE  STORE_NBR        FAMILY  SALES  ONPROMOTION
0  1945944  2016-01-01          1    AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1     BABY CARE    0.0            0
2  1945946  2016-01-01          1        BEAUTY    0.0            0
3  1945947  2016-01-01          1     BEVERAGES    0.0            0
4  1945948  2016-01-01          1         BOOKS    0.0            0
5  1945949  2016-01-01          1  BREAD/BAKERY    0.0            0
6  1945950  2016-01-01          1   CELEBRATION    0.0            0

In [34]:
df.tail(4)

,ID,DATE,STORE_NBR,FAMILY,SALES,ONPROMOTION
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [ ]:
df_oil.sample(5)   # Randomly picks any rows

           date  dcoilwtico
173  2013-08-30      107.98
993  2016-10-21       50.61
702  2015-09-10       45.85
417  2014-08-07       97.34
762  2015-12-03       41.08

In [37]:
df_oil.isnull().sum()

date           0
dcoilwtico    43
dtype: int64

# **Data Cleaning**
_follow the order_
- **Type casting**
- **Handling Missing Data (Null val.)**  _(if taking mean earlier to fill data look for outlier 1st)_
- **Inconsistent text & typos**
- **Duplicates**
- **Outliers**

### **1. Type Cast (datatype)**

In [68]:
run_time = pd.read_excel('../data/Run Times.xlsx')
run_time

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [69]:
run_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      object
 4   Run Date      5 non-null      datetime64[ns]
 5   Race Date     5 non-null      datetime64[ns]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      object
dtypes: bool(1), datetime64[ns](2), float64(1), object(4)
memory usage: 417.0+ bytes

In [70]:
run_time.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                     object
dtype: object

In [71]:
run_time['Fee'] = pd.to_numeric(run_time['Fee'].str.replace('$', ''))
run_time

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [72]:
run_time_c = run_time.copy()
run_time_c

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [73]:
run_time.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

When converting strings to numeric, invalid data causes errors.
- `errors='raise'`: Crashes on invalid values
- `errors='coerce'`: Replaces invalid values with NaN

In [74]:
# run_time['Warm Up Time'] = pd.to_numeric(run_time['Warm Up Time']) - this will throw error for index 2 - '3 min'
run_time['Warm Up Time'] = pd.to_numeric(run_time['Warm Up Time'], errors = 'coerce')
run_time

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,NaN,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2.0,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [75]:
run_time.dtypes

Name                    object
Run Time               float64
Warm Up Time           float64
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [76]:
run_time_c['Warm Up Time'] = run_time_c['Warm Up Time'].str.replace('min', '')
run_time_c

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,NaN,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,NaN,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,NaN,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,NaN,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

### **2.0 Missing Data**

In [103]:
df_stud = pd.read_excel('../data/Student Grades.xlsx')
df_stud02 = df_stud.copy()
df_stud

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
81      NaN               NaN       NaN    NaN
82  Bennett               NaN       NaN    NaN
83      NaN               EDA    Junior   84.0
84    Gavin               EDA    Senior    NaN
85   Calvin               NaN       NaN  100.0

[86 rows x 4 columns]

In [104]:
df_stud.describe()

            Grade
count   82.000000
mean    85.707317
std     15.527346
min     45.000000
25%     81.000000
50%     85.000000
75%     90.000000
max    200.000000

In [105]:
df_stud.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [106]:
df_stud[df_stud.isna().any(axis = 1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

In [107]:
df_stud

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
81      NaN               NaN       NaN    NaN
82  Bennett               NaN       NaN    NaN
83      NaN               EDA    Junior   84.0
84    Gavin               EDA    Senior    NaN
85   Calvin               NaN       NaN  100.0

[86 rows x 4 columns]

In [ ]:
df_stud.dropna(how = 'all', inplace = True)   # use: inplace = True to replace this in the dataframe
df_stud.dropna(subset = ['Student', 'Class'], inplace = True)
df_stud = df_stud[df_stud['Student'] != 'Bennet']
df_stud

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
77    Aaron               EDA    Junior   85.0
78  Charles               EDA    Junior   93.0
79   Connor               EDA    Junior   91.0
80    Riley               EDA    Junior   87.0
84    Gavin               EDA    Senior    NaN

[82 rows x 4 columns]

In [111]:
df_stud.isna().sum()

Student    0
Class      0
Year       3
Grade      2
dtype: int64

### **2.1. Filling Missing Values**

In [119]:
df_stud['Grade'].fillna(df_stud['Grade'].mean(), inplace = True)
df_stud

C:\Users\Shreyit\AppData\Local\Temp\ipykernel_19820\2722594578.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_stud['Grade'].fillna(df_stud['Grade'].mean(), inplace = True)

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman  86.00
1    Olivia  Freshman Seminar  Freshman  86.00
2      Noah  Freshman Seminar  Freshman  86.00
3    Sophia  Freshman Seminar  Freshman  87.00
4      Liam  Freshman Seminar  Freshman  90.00
..      ...               ...       ...    ...
77    Aaron               EDA    Junior  85.00
78  Charles               EDA    Junior  93.00
79   Connor               EDA    Junior  91.00
80    Riley               EDA    Junior  87.00
84    Gavin               EDA    Senior  85.55

[82 rows x 4 columns]

In [118]:
df_stud.isna().sum()

Student    0
Class      0
Year       3
Grade      0
dtype: int64

In [120]:
df_stud[df_stud['Class'] == 'Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar       NaN   88.0
8    William  Freshman Seminar       NaN   89.0
9      Ethan  Freshman Seminar       NaN   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [138]:
df_stud['Year'] = np.where((df_stud['Year'].isna()) & (df_stud['Class']=='Freshman Seminar'), 'Freshman', df_stud['Year'])
df_stud

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman  86.00
1    Olivia  Freshman Seminar  Freshman  86.00
2      Noah  Freshman Seminar  Freshman  86.00
3    Sophia  Freshman Seminar  Freshman  87.00
4      Liam  Freshman Seminar  Freshman  90.00
..      ...               ...       ...    ...
77    Aaron               EDA    Junior  85.00
78  Charles               EDA    Junior  93.00
79   Connor               EDA    Junior  91.00
80    Riley               EDA    Junior  87.00
84    Gavin               EDA    Senior  85.55

[82 rows x 4 columns]

In [139]:
df_stud.isna().sum()

Student    0
Class      0
Year       0
Grade      0
dtype: int64